### ISSUE TITLE
Unnecessary code

### ISSUE THREAD

**Issue by eknkc** [faizbaraja/CocoaPodTest#1]
Why do we liston to these events?

https://github.com/faizbaraja/CocoaPodTest/blob/1a7dbca949bcb108dffc1cccc0a37edeb5352654/BarajaFramework/whatsNewService.html#L72-L85

**Comment by faizbaraja** [comment]
this is the html that created by the other dev..

i haven't remove the unnecessary code yet. 

i will remove it now..

**Comment by eknkc** [comment]
We have provided that HTML as a reference for you to see how they approached the issue. Please do not base your code on the previous work as it was just a hacky solution from one of our users.

Also, I've seen that you removed the lines but not the one that I did not mark: 
https://s3.eknkc.com/x/2021/03/10/1BcNFLQCXH.png

This is obviously another one of unnecessary event handlers. Why not remove it? Do I need to point to every single tiny detail like this? I know this is not important regarding to the functionality of the module but we need to create a high quality SDK for our users and you should be ahead of me while dealing with these kind of things.

**Comment by faizbaraja** [comment]
well noted...sorry for the mistake.. ill be more careful..

thanks for the advice
